spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth-hw
    username: postgres
    password: Sema3105=
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

