spring:
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/ticket-hw
    username: postgres
    password: Sema3105=
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate:
      show_sql: true
      format_sql: true
server:
  port: 8081